### ISSUE TITLE
'RouteMapDB' object has no attribute 'create_tables'

### ISSUE THREAD

**Issue by hholzgra** [waymarkedtrails/waymarkedtrails-backend#4]
Using both latest master checkout of waymarkedtrails-backend and osgende I can perform the general dbimport, but when trying to process hiking routes I run into `AttributeError: 'RouteMapDB' object has no attribute 'create_tables'`

```
/home/maposmatic/styles/waymarkedtrails-backend # ./makedb.py hiking create
/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/functions.py:65: SAWarning: The GenericFunction 'st_makeline' is already registered and is going to be overridden.
  util.warn(
Traceback (most recent call last):
  File "./makedb.py", line 198, in <module>
    db = MapStyleDb(options)
  File "./makedb.py", line 98, in __init__
    self.mapdb = mapdb_pkg.create_mapdb(site_config, options)
  File "/home/maposmatic/styles/waymarkedtrails-backend/wmt_db/maptype/routes.py", line 68, in create_mapdb
    db = RouteMapDB(options, site_config)
  File "/home/maposmatic/styles/waymarkedtrails-backend/wmt_db/maptype/routes.py", line 30, in __init__
    super().__init__(config)
  File "/usr/local/lib/python3.8/dist-packages/osgende/mapdb.py", line 51, in __init__
    self.tables = self.create_tables()
AttributeError: 'RouteMapDB' object has no attribute 'create_tables'
```

**Comment by hholzgra** [comment]
Ignore this for now, turns out I should probably clone osgende from waymarkedtrails, not lonvia ...

**Comment by hholzgra** [comment]
That unfortunately wasn't it, same error  in osgende/mapdb.py ... :(

**Comment by hholzgra** [comment]
Problem seems to have started with changeset 09d61395888c9e80df723c4e1b890bc8705cca5

https://github.com/waymarkedtrails/waymarkedtrails-backend/commit/09d61395888c9e80df723c4e1b890bc8705cca5

**Comment by lonvia** [comment]
You have to use the [rework-mapdb branch of osgende](https://github.com/waymarkedtrails/osgende/tree/rework-mapdb) with the waymarkedtrail-backend repository. I've just pushed all the latest changes to both.

Sorry about the in-between state. I had hoped to had this done sooner.

**Comment by hholzgra** [comment]
Works fine now, and the `The GenericFunction 'st_makeline' is already registered` warning is gone now, too :)
