### ISSUE TITLE
Readme should mention that sqlalchemy >=1.4 is needed

### ISSUE THREAD

**Issue by hholzgra** [waymarkedtrails/waymarkedtrails-backend#7]
The README says:

```
On Ubuntu 20.04/Debian 11 the following should install all prerequisits:

sudo apt install python3-psycopg2 python3-shapely python3-sqlalchemy-ext \
                 python3-geoalchemy2 ....
```

but due to the dependency on osgende, and that in turn requiring sqlalchemy 1.4, following the instructions in the README will lead to 

```
AttributeError: type object 'URL' has no attribute 'create'
```
errors, as Debian 11 and Ubuntu 20.04 still have sqlalchemy 1.3 packaged and not upgraded to 1.4 yet.

**Comment by lonvia** [comment]
That's a rather recent development. I've updated the README with the package installation instructions currently used on production.
